server:
  port: ${RIOS_SERVER_PORT:8085}

springdoc:
  swagger-ui:
    path: /docs


spring:
  application:
    name: msvc-rios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RIOS_DB_HOST:localhost}:${RIOS_DB_PORT:3306}/${DB_NAME:riosdb}
    username: ${DB_USER:root}
    password: ${RIOS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: ${RIOS_EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}


