server:
  port: ${PECES_SERVER_PORT:8084}

springdoc:
  swagger-ui:
    path: /docs


spring:
  application:
    name: msvc-peces
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PECES_DB_HOST:localhost}:${PECES_DB_PORT:3306}/${DB_NAME:pecesdb}
    username: ${DB_USER:root}
    password: ${PECES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: ${PECES_EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}


