server:
  port: ${VOLUNTARIOS_SERVER_PORT:8083}

springdoc:
  swagger-ui:
    path: /docs

spring:
  application:
    name: msvc-voluntarios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${VOLUNTARIOS_DB_HOST:localhost}:${VOLUNTARIOS_DB_PORT:3306}/${DB_NAME:voluntariosdb}
    username: ${DB_USER:root}
    password: ${VOLUNTARIOS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: ${VOLUNTARIOS_EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

admin:
  email: ${ADMIN_EMAIL:riverspainproyecto@gmail.com}